//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socialworld.Models.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public evento()
        {
            this.contactoes = new HashSet<contacto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public string direccion { get; set; }
        public long fechainicio { get; set; }
        public long fechafinal { get; set; }
        public bool cancelado { get; set; }
        public int idc { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<contacto> contactoes { get; set; }
    }
}
