//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socialworld.Models.Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EVENTOSBDEntities : DbContext
    {
        public EVENTOSBDEntities()
            : base("name=EVENTOSBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tarifa> tarifas { get; set; }
        public DbSet<cliente> clientes { get; set; }
        public DbSet<contacto> contactoes { get; set; }
        public DbSet<evento> eventoes { get; set; }
    }
}
