//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socialworld.Models.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifa
    {
        public decimal contacto { get; set; }
        public decimal evento { get; set; }
    }
}
